server {
    listen       80;
    server_name  localhost;
    root         /var/www/html;
    index        index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;

    # Deny access to hidden files
    location ~ /\. {
        deny all;
    }
}
