version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    networks:
      - frontend

  api:
    image: python:3.11-alpine
    working_dir: /app
    command: sh -c "pip install flask && python app.py"
    volumes:
      - ./api:/app
      - ./backend/message.txt:/data/message.txt
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
